# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwiQUiy1cg-rbkGx3P5FOFTjXZ8fYCK4
"""

import requests
import pandas as pd
from google.colab import files

def cao_va_xuat_csv_vinamilk():
    app_id = "6450284112"
    region = "vn"
    reviews_data = []

    print("Bước 1: Đang tiến hành kết nối và thu thập dữ liệu từ App Store...")

    for page in range(1, 11):
        url = f"https://itunes.apple.com/{region}/rss/customerreviews/page={page}/id={app_id}/sortby=mostrecent/json"
        try:
            response = requests.get(url)
            if response.status_code != 200:
                break

            data = response.json()
            entries = data.get('feed', {}).get('entry', [])

            if not entries:
                break
            if isinstance(entries, dict):
                entries = [entries]

            start_index = 1 if page == 1 else 0
            for entry in entries[start_index:]:
                review = {
                    "Người đánh giá (Username)": entry.get('author', {}).get('name', {}).get('label'),
                    "Link Profile": entry.get('author', {}).get('uri', {}).get('label'),
                    "Tiêu đề (Headline)": entry.get('title', {}).get('label'),
                    "Nội dung chi tiết": entry.get('content', {}).get('label'),
                    "Số sao": int(entry.get('im:rating', {}).get('label', 0)),
                    "Thời gian ID": entry.get('id', {}).get('label'),
                    "Bối cảnh (Phiên bản App)": entry.get('im:version', {}).get('label'),
                    "Quốc gia": region.upper()
                }
                reviews_data.append(review)
            print(f"Đã quét xong dữ liệu trang {page}/10")
        except Exception:
            break

    if reviews_data:
        print(f"\n Bước 2: Tìm thấy tất cả {len(reviews_data)} dòng dữ liệu.")
        df = pd.DataFrame(reviews_data)

        df = df.fillna("")

        filename = "reviews_vinamilk_chuan.csv"

        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"Đã đóng gói thành công file '{filename}'")

        print("Trình duyệt đang tiến hành tự động tải file về máy tính của bạn...")
        files.download(filename)
    else:
        print("Không thu thập được dữ liệu. Vui lòng kiểm tra lại trạng thái mạng của bạn.")

cao_va_xuat_csv_vinamilk()